#' Compute bootstrap variability bands
#'
#' Compute variability bands for the optimized trend filtering estimate via the
#' sample quantiles of the bootstrap ensemble generated by
#' [`bootstrap_trendfilter()`].
#'
#' @param obj An object of class [`'bootstrap_tf'`][bootstrap_trendfilter()].
#' @param level The level of the pointwise variability bands. Defaults to
#' `level = 0.95`.
#' @return A tibble with column set:
#' `c("x","bootstrap_lower_band","bootstrap_upper_band")`.
#'
#' @seealso [`bootstrap_trendfilter()`]
#'
#' @references
#' \enumerate{
#' \item{Politsch et al. (2020a).
#' \href{https://academic.oup.com/mnras/article/492/3/4005/5704413}{
#' Trend filtering – I. A modern statistical tool for time-domain astronomy and
#' astronomical spectroscopy}. \emph{MNRAS}, 492(3), p. 4005-4018.} \cr
#' \item{Politsch et al. (2020b).
#' \href{https://academic.oup.com/mnras/article/492/3/4019/5704414}{
#' Trend Filtering – II. Denoising astronomical signals with varying degrees of
#' smoothness}. \emph{MNRAS}, 492(3), p. 4019-4032.}}
#'
#' @examples
#' data(quasar_spectrum)
#' head(spec)
#'
#' sure_tf <- sure_trendfilter(spec$log10_wavelength, spec$flux, spec$weights)
#' boot_tf <- bootstrap_trendfilter(sure_tf, bootstrap_algorithm = "parametric")
#' bands <- vbands(boot_tf)
#' @importFrom dplyr tibble
#' @export
vbands <- function(obj, level = 0.95) {
  stopifnot(any(class(obj) %in% c("bootstrap_tf")))
  stopifnot(level > 0 & level < 1)

  bootstrap_lower_band <- apply(
    obj$ensemble,
    1,
    quantile,
    probs = (1 - level) / 2
  )

  bootstrap_upper_band <- apply(
    obj$ensemble,
    1,
    quantile,
    probs = 1 - (1 - level) / 2
  )

  tibble(
    x = obj$x_eval,
    bootstrap_lower_band = bootstrap_lower_band,
    bootstrap_upper_band = bootstrap_upper_band
  )
}
