#' Compute bootstrap variability bands
#'
#' Compute variability bands for the optimized trend filtering estimate via the
#' sample quantiles of the bootstrap ensemble generated by
#' [`bootstrap_trendfilter()`].
#'
#' @param obj An object of class '[`bootstrap_tf`][bootstrap_trendfilter()]'.
#' @param level The level of the pointwise variability bands. Defaults to
#' `level = 0.95`.
#' @return A tibble with column set:
#' `c("x","bootstrap_lower_band","bootstrap_upper_band")`.
#'
#' @seealso [`bootstrap_trendfilter()`]
#'
#' @references
#' \enumerate{
#' \item{Politsch et al. (2020a).
#' \href{https://academic.oup.com/mnras/article/492/3/4005/5704413}{
#' Trend filtering – I. A modern statistical tool for time-domain astronomy and
#' astronomical spectroscopy}. \emph{MNRAS}, 492(3), p. 4005-4018.} \cr
#' \item{Politsch et al. (2020b).
#' \href{https://academic.oup.com/mnras/article/492/3/4019/5704414}{
#' Trend Filtering – II. Denoising astronomical signals with varying degrees of
#' smoothness}. \emph{MNRAS}, 492(3), p. 4019-4032.}}
#'
#' @examples
#' # Example 1: Phase-folded light curve of an eclipsing binary star system
#' #
#' # The apparent brightness over time of a star system that has two suns
#' # that regularly eclipse one another from our vantage point on Earth. Here,
#' # the time series is stacked according to the orbital period of the binary
#' # system, with the primary eclipse occuring at `phase = 0` and the input
#' # domain ranging from -0.5 to 0.5.
#'
#' data(eclipsing_binary)
#' head(EB)
#'
#' cv_tf <- cv_trendfilter(
#'   x = EB$phase,
#'   y = EB$flux,
#'   weights = 1 / EB$std_err^2,
#'   optimization_params = list(
#'     max_iter = 1e4,
#'     obj_tol = 1e-6,
#'     thinning = TRUE
#'   )
#' )
#'
#' pred_tf <- predict(
#'   cv_tf,
#'   validation_error_metric = "MAE",
#'   lambda_choice = "lambda_1se",
#'   nx_eval = 1500L
#' )
#'
#' boot_tf <- bootstrap_trendfilter(pred_tf, "nonparametric")
#' bands <- vbands(boot_tf)
#'
#'
#' # Example 2: The "Lyman-alpha forest" in the spectrum of a distant quasar
#'
#' data(quasar_spectrum)
#' head(spec)
#'
#' sure_tf <- sure_trendfilter(spec$log10_wavelength, spec$flux, spec$weights)
#' pred_tf <- predict(sure_tf)
#'
#' boot_tf <- bootstrap_trendfilter(pred_tf, "parametric")
#' bands <- vbands(boot_tf)
#' @importFrom dplyr tibble
#' @export
vbands <- function(obj, level = 0.95) {
  stopifnot(any(class(obj) == "boot_tf"))
  stopifnot(level > 0 & level < 1)

  bootstrap_lower_band <- apply(
    obj$ensemble,
    1,
    quantile,
    probs = (1 - level) / 2
  )

  bootstrap_upper_band <- apply(
    obj$ensemble,
    1,
    quantile,
    probs = 1 - (1 - level) / 2
  )

  tibble(
    x = obj$x_eval,
    bootstrap_lower_band = bootstrap_lower_band,
    bootstrap_upper_band = bootstrap_upper_band
  )
}
